version: '3.8'

services:
  active-history-service:
    image: 009160040466.dkr.ecr.ap-northeast-2.amazonaws.com/learn-run/active-history-service:latest
    container_name: active-history-service
    env_file:
      - .env
    networks:
      - shared-net

networks:
  shared-net:
    external: true